/* ==========================================================================
   PART 2 TASK (d): PHYSICAL DATABASE DESIGN
   Project: AVANTIVE Corporation Database
   Description: DDL Script to create all tables with constraints
   ========================================================================== */

-- A. CLEANUP (Drop tables in reverse order of dependencies to avoid errors)
-- Remove the comment dashes below if you need to clear the database first
/*
DROP TABLE OrderLines CASCADE CONSTRAINTS;
DROP TABLE Orders CASCADE CONSTRAINTS;
DROP TABLE CarModel_Parts CASCADE CONSTRAINTS;
DROP TABLE Parts CASCADE CONSTRAINTS;
DROP TABLE CarModels CASCADE CONSTRAINTS;
DROP TABLE WholesaleCustomers CASCADE CONSTRAINTS;
DROP TABLE RetailCustomers CASCADE CONSTRAINTS;
DROP TABLE Customers CASCADE CONSTRAINTS;
DROP TABLE Administrators CASCADE CONSTRAINTS;
DROP TABLE TechnicalSupport CASCADE CONSTRAINTS;
DROP TABLE SalesRepresentatives CASCADE CONSTRAINTS;
DROP TABLE Employees CASCADE CONSTRAINTS;
DROP TABLE Departments CASCADE CONSTRAINTS;
*/

-- ==========================================================================
-- B. LOOKUP TABLES
-- ==========================================================================

-- 1. Departments [Source: 30]
-- Constraint: Must be one of the 5 specific departments listed in the requirement.
CREATE TABLE Departments (
    DeptID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    DeptName VARCHAR2(50) NOT NULL CHECK (DeptName IN ('Administration', 'Marketing', 'Sales', 'Shipping', 'Purchasing'))
);

-- ==========================================================================
-- C. EMPLOYEE HIERARCHY (Supertype/Subtype Strategy)
-- ==========================================================================

-- 2. Employees (Supertype) [Source: 30-31]
-- Holds common attributes for all staff.
CREATE TABLE Employees (
    EmployeeID NUMBER PRIMARY KEY,
    Name VARCHAR2(100) NOT NULL,
    HomeAddress VARCHAR2(255),
    PhoneNumber VARCHAR2(20),
    Salary NUMBER(10, 2),
    TaxID VARCHAR2(50),
    DeptID NUMBER,
    EmployeeType VARCHAR2(20) CHECK (EmployeeType IN ('Sales', 'Tech', 'Admin')), -- Discriminator
    CONSTRAINT FK_Emp_Dept FOREIGN KEY (DeptID) REFERENCES Departments(DeptID)
);

-- 3. Sales Representatives (Subtype) [Source: 33]
-- Inherits from Employees. Specific attribute: Commission.
CREATE TABLE SalesRepresentatives (
    EmployeeID NUMBER PRIMARY KEY,
    CommissionRate NUMBER(5, 4), -- e.g., 0.05 for 5%
    CONSTRAINT FK_Sales_Emp FOREIGN KEY (EmployeeID) REFERENCES Employees(EmployeeID) ON DELETE CASCADE
);

-- 4. Technical Support (Subtype) [Source: 33-34]
-- Inherits from Employees. Specific attribute: Expertise Area.
CREATE TABLE TechnicalSupport (
    EmployeeID NUMBER PRIMARY KEY,
    ExpertiseArea VARCHAR2(100), -- e.g., 'Drivetrain', 'Electrical Systems'
    CONSTRAINT FK_Tech_Emp FOREIGN KEY (EmployeeID) REFERENCES Employees(EmployeeID) ON DELETE CASCADE
);

-- 5. Administrators (Subtype) [Source: 35]
-- Inherits from Employees. Specific attributes: Title, Bonus.
CREATE TABLE Administrators (
    EmployeeID NUMBER PRIMARY KEY,
    Title VARCHAR2(50),
    Bonus NUMBER(10, 2),
    CONSTRAINT FK_Admin_Emp FOREIGN KEY (EmployeeID) REFERENCES Employees(EmployeeID) ON DELETE CASCADE
);

-- ==========================================================================
-- D. CUSTOMER HIERARCHY (Supertype/Subtype Strategy)
-- ==========================================================================

-- 6. Customers (Supertype) [Source: 15, 23]
-- Holds common attributes for all customers.
CREATE TABLE Customers (
    CustomerID NUMBER PRIMARY KEY,
    Name VARCHAR2(100) NOT NULL,
    Address VARCHAR2(255),
    PhoneNumber VARCHAR2(20),
    DefaultShippingAddress VARCHAR2(255),
    DateLastPurchase DATE,
    DateLastPayment DATE,
    CustomerType VARCHAR2(20) CHECK (CustomerType IN ('Retail', 'Wholesale')) -- Discriminator [Source: 26]
);

-- 7. Retail Customers (Subtype) [Source: 24]
-- Specific attributes: Credit Card info, Email.
CREATE TABLE RetailCustomers (
    CustomerID NUMBER PRIMARY KEY,
    CreditCardNumber VARCHAR2(20),
    CreditCardType VARCHAR2(20),
    ExpirationDate DATE,
    EmailAddress VARCHAR2(100),
    CONSTRAINT FK_Retail_Cust FOREIGN KEY (CustomerID) REFERENCES Customers(CustomerID) ON DELETE CASCADE
);

-- 8. Wholesale Customers (Subtype) [Source: 25]
-- Specific attributes: Contact Person, PO info, Discount, Tax info.
CREATE TABLE WholesaleCustomers (
    CustomerID NUMBER PRIMARY KEY,
    ContactName VARCHAR2(100),
    ContactPhone VARCHAR2(20),
    ContactEmail VARCHAR2(100),
    PurchaseOrderNumber VARCHAR2(50),
    PurchaseOrderDate DATE,
    DiscountPercentage NUMBER(5, 4) CHECK (DiscountPercentage BETWEEN 0 AND 1), -- e.g., 0.20 for 20%
    BillingAddress VARCHAR2(255),
    TaxStatus VARCHAR2(50), 
    TaxIdentificationNumber VARCHAR2(50),
    CONSTRAINT FK_Wholesale_Cust FOREIGN KEY (CustomerID) REFERENCES Customers(CustomerID) ON DELETE CASCADE
);

-- ==========================================================================
-- E. INVENTORY SYSTEM
-- ==========================================================================

-- 9. Car Models [Source: 12]
CREATE TABLE CarModels (
    CarModelID NUMBER PRIMARY KEY,
    Manufacturer VARCHAR2(50),
    ModelName VARCHAR2(50),
    ManufactureYear NUMBER(4)
);

-- 10. Parts [Source: 13]
CREATE TABLE Parts (
    PartID NUMBER PRIMARY KEY,
    Description VARCHAR2(255),
    UnitPrice NUMBER(10, 2), -- Current base price
    QuantityOnHand NUMBER(10) DEFAULT 0
);

-- 11. CarModel_Parts (Junction Table) [Source: 14]
-- Implements the M:N relationship between Cars and Parts.
CREATE TABLE CarModel_Parts (
    CarModelID NUMBER,
    PartID NUMBER,
    PRIMARY KEY (CarModelID, PartID),
    CONSTRAINT FK_CMP_Car FOREIGN KEY (CarModelID) REFERENCES CarModels(CarModelID),
    CONSTRAINT FK_CMP_Part FOREIGN KEY (PartID) REFERENCES Parts(PartID)
);

-- ==========================================================================
-- F. ORDER PROCESSING SYSTEM
-- ==========================================================================

-- 12. Orders [Source: 19-20]
-- Links Customer and Employee (Sales Rep).
CREATE TABLE Orders (
    OrderNumber NUMBER PRIMARY KEY,
    OrderDate DATE DEFAULT SYSDATE,
    ShippingAddress VARCHAR2(255),
    BillingAddress VARCHAR2(255),
    -- Status constraint as per Source 20
    OrderStatus VARCHAR2(20) CHECK (OrderStatus IN ('Open', 'Closed', 'Cancel')), 
    -- Financial fields
    OrderSubtotal NUMBER(12, 2) DEFAULT 0,
    OrderTax NUMBER(12, 2) DEFAULT 0,
    ShippingCost NUMBER(12, 2) DEFAULT 0,
    OrderTotalCost NUMBER(12, 2) DEFAULT 0,
    OrderTotalPaid NUMBER(12, 2) DEFAULT 0,
    ShippingDate DATE,
    -- Foreign Keys
    CustomerID NUMBER NOT NULL,
    SalesRepID NUMBER NOT NULL, -- Must be an employee who is a Sales Rep
    CONSTRAINT FK_Order_Cust FOREIGN KEY (CustomerID) REFERENCES Customers(CustomerID),
    -- Linking specifically to SalesRepresentatives table ensures the employee is authorized for sales
    CONSTRAINT FK_Order_SalesRep FOREIGN KEY (SalesRepID) REFERENCES SalesRepresentatives(EmployeeID)
);

-- 13. OrderLines (Order Details) [Source: 19]
-- Implements M:N between Orders and Parts, with transaction-specific data.
CREATE TABLE OrderLines (
    OrderNumber NUMBER,
    PartID NUMBER,
    Quantity NUMBER(10) CHECK (Quantity > 0),
    ListPrice NUMBER(10, 2), -- Price frozen at time of order
    ExtendedLineTotal NUMBER(12, 2), -- Quantity * ListPrice
    PRIMARY KEY (OrderNumber, PartID),
    CONSTRAINT FK_OL_Order FOREIGN KEY (OrderNumber) REFERENCES Orders(OrderNumber),
    CONSTRAINT FK_OL_Part FOREIGN KEY (PartID) REFERENCES Parts(PartID)
);

-- End of DDL Script